# roles/mysql_keepalived/tasks/main.yml

- name: install killall
  yum:
    name: psmisc
    state: present

- name: install lvs
  yum:
    name: ipvsadm
    state: present

- name: install keepalived
  yum:
    name: keepalived
    state: present

- name: config keepalived
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf

- name: copy selinux's module file
  copy:
    src: killall_httpd.pp
    dest: /tmp/killall_httpd.pp

- name: set selinux for killall & httpd
  shell: semodule -i /tmp/killall_httpd.pp

- name: restart keepalived
  service:
    name: keepalived
    state: restarted
