--- 
# roles/k8s/tasks/main.yml

- name: Get kubernetes.repo
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Disable selinux
  selinux:
    state: disabled

- name: Install kubelet
  yum:
    name: "{{ packages }}"
    disable_excludes: kubernetes
  environment:
    all_proxy: socks5://192.168.16.82:1080
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_file: /etc/sysctl.d/k8s.conf
- sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    sysctl_file: /etc/sysctl.d/k8s.conf

# firewalld issues
- name: Accept INPUT by default
  shell: firewall-cmd --permanent --zone=public --set-target=ACCEPT

- name: Accept FORWARD to 10.244.0.0/16 by default
  shell: firewall-cmd --permanent --zone=public --direct --add-rule ipv4 filter FORWARD 1 -d 10.244.0.0/16 -j ACCEPT

- name: Accept FORWARD from 10.244.0.0/16 by default
  shell: firewall-cmd --permanent --zone=public --direct --add-rule ipv4 filter FORWARD 1 -s 10.244.0.0/16 -j ACCEPT

- name: Completely reload firewalld
  shell: firewall-cmd --complete-reload

- name: Start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes

