# playbook for docker

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
- name: set up the stable docker repository
  shell: yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker-ce
  yum:
    name: docker-ce
    state: present

- name: make directory /etc/docker
  file:
    path: /etc/docker
    owner: root
    group: root
    mode: 0755
    state: directory

- name: create /etc/docker/daemon.json
  shell: "echo -e '{\n  \"storage-driver\": \"devicemapper\"\n}' > /etc/docker/deamon.json"

- name: start dockerd
  service:
    name: docker
    state: restarted
